# SLF4J Simple Logger Configuration
# Désactiver les logs pour certains packages
org.slf4j.simpleLogger.defaultLogLevel=ERROR
org.slf4j.simpleLogger.log.org.hibernate=ERROR
org.slf4j.simpleLogger.log.org.springframework=ERROR
org.slf4j.simpleLogger.log.org.springframework.orm=ERROR
org.slf4j.simpleLogger.log.org.springframework.context=ERROR
org.slf4j.simpleLogger.log.com.mysql=ERROR
